build_name: psx-full-eng
completed_platforms:
- psx
- psx
current_platform: null
failed_platforms:
- psx
last_updated: '2025-11-06T13:59:00.721490'
started_at: '2025-10-30T09:21:49.683183'
status: completed
