build_name: wswanc-test
completed_platforms:
- wswanc
current_platform: null
failed_platforms: []
last_updated: '2025-11-19T20:05:03.135249'
started_at: '2025-11-19T20:04:58.628880'
status: completed
