build_name: saturn-full-eng
completed_platforms:
- saturn
- saturn
- saturn
- saturn
- saturn
- saturn
current_platform: null
failed_platforms:
- saturn
last_updated: '2025-10-22T16:54:18.115241'
started_at: '2025-10-21T09:42:03.512973'
status: completed
