build_name: nds-test
completed_platforms:
- nds
- nds
- nds
current_platform: null
failed_platforms:
- nds
last_updated: '2025-11-20T12:03:06.049406'
started_at: '2025-11-19T21:33:43.097366'
status: completed
